---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-iot
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: home-iot
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: https://dispiny.github.io/home-iot/
    targetRevision: "1.0.5"
    chart: home-iot
  sources: []
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
      - PruneLast=true
  ignoreDifferences:
    - kind: ConfigMap
    - kind: Secret
    - group: networking.k8s.io
      kind: Ingress
