---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: application/
    repoURL: https://github.com/dispiny/local-kubernetes-manifest.git
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
