apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  source:
    path: vault/
    repoURL: "https://github.com/dispiny/local-kubernetes-manifest.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false # 리소스 삭제 방지
      selfHeal: true
    syncOptions:
      - Validate=false
      - PruneLast=true
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: networking.k8s.io
      kind: Ingress # 이 경우 Ingress를 포함하여 관리
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-iot
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: home-iot
    server: https://kubernetes.default.svc
  source:
    path: ""
    repoURL: https://dispiny.github.io/home-iot/
    targetRevision: "1.0.5"
    chart: home-iot
  sources: []
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - kind: ConfigMap
    - kind: Secret
    - group: networking.k8s.io
      kind: Ingress
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ghost
    server: https://kubernetes.default.svc
  source:
    path: ghost/
    repoURL: https://github.com/dispiny/local-kubernetes-manifest.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: prometheus
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: "27.1.0"
      chart: prometheus
      path: ""
    - repoURL: https://github.com/dispiny/local-kubernetes-manifest.git
      targetRevision: HEAD
      path: prometheus/
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---