---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: prometheus
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: "27.1.0"
      chart: prometheus
      path: ""
    - repoURL: https://github.com/dispiny/local-kubernetes-manifest.git
      targetRevision: HEAD
      path: prometheus/
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
