apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: vault
spec:
  method: kubernetes # Authentication Methods - 쿠버네티스 인증
  mount: kubernetes # Authentication Methods Name
  kubernetes:
    role: vso # vault에서 설정한 role name
    serviceAccount: vso-sa # kubernetes serviceaccount name
