---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
spec:
  destination:
    name: ""
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://bitnami.com
      targetRevision: "11.6.16"
      chart: nginx-ingress-controller
      path: ""
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
