---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Prune=confirm
spec:
  destination:
    name: ""
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: "4.12.2"
      chart: ingress-nginx
      path: ""
      helm:
        values: |-
          controller:
            service:
              type: NodePort
              nodePort:
                http: 30525
                https: 30719
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
