apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: obsidian-secret
spec:
  type: kv-v2 # 시크릿 type 입력
  mount: kvv2 # 마운트 할 Secret Engine name 입력
  path: obsidian_couchdb # 시크릿을 생성할 때 설정한 secret name을 설정한다.
  destination:
    name: obsidian-vault-couchdb # kubernetes secret으로 생성할 kubernetes secret name 입력
    create: true # kubernetes secret으로 생성여부
  refreshAfter: 60s # vault secret과 kuberentes secret 동기화 시간 입력
  vaultAuthRef: vault-auth # 2번에서 생성한 VaultAuth name 입력
