apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
spec:
  # address to the Vault server.
  address: http://vault.vault.svc.cluster.local:8200
  skipTLSVerify: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: vault
spec:
  method: kubernetes # Authentication Methods - 쿠버네티스 인증
  mount: vso # Authentication Methods Name
  kubernetes:
    role: vso # vault에서 설정한 role name
    serviceAccount: ghost-sa # kubernetes serviceaccount name
