---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: n8n
    server: https://kubernetes.default.svc
  sources:
    - path: n8n/
      repoURL: https://github.com/dispiny/local-kubernetes-manifest.git
      targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PruneLast=true
